[package]
name = "genai-vectors"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A production-grade vector database for similarity search"
repository = "https://github.com/your-org/genai-vectors"
license = "MIT"
readme = "README.md"
keywords = ["vector", "database", "similarity", "search", "ai"]
categories = ["database", "algorithms"]

[[bin]]
name = "genai-vectors"
path = "src/main.rs"

[lib]
name = "genai_vectors"
path = "src/lib.rs"

[dependencies]
# faiss = { version = "0.12.1", default-features = false, features = ["static"] }
# Commenting out Faiss for now due to OpenMP dependency on macOS

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Web framework
axum        = { version = "0.7", features = ["json", "macros"] }
tokio       = { version = "1.38", features = ["rt-multi-thread", "macros"] }

# Serialization
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"

# Utilities
uuid        = { version = "1", features = ["v4"] }
chrono      = { version = "0.4.31", features = ["serde"] }
clap        = { version = "4.0", features = ["derive"] }
bytes       = "1.6"

# Logging
tracing     = "0.1"
tracing-subscriber = "0.3"

# S3-compatible client (MinIO or AWS)
aws-config  = { version = "1.1", optional = true }
aws-sdk-s3  = { version = "1.19", features = ["behavior-version-latest"], optional = true }

[dev-dependencies]
tokio-test = "0.4"

[features]
default = ["s3"]
s3 = ["aws-config", "aws-sdk-s3"]
