apiVersion: skaffold/v4beta11
kind: Config
profiles:
  - name: minio
    deploy:
      helm:
        releases:
          - name: minio
            namespace: genai-vectors
            createNamespace: true
            remoteChart: bitnami/minio
            valuesFiles:
              - k8s/minio.values.yaml

  - name: vector-store
    build:
      tagPolicy:
        envTemplate:
          template: "v1"
      artifacts:
        - image: hv-local/vector-store-api
          docker:
            dockerfile: Dockerfile.api
        - image: hv-local/vector-store-indexer
          docker:
            dockerfile: Dockerfile.indexer
      local:
        push: false
        concurrency: 1
    deploy:
      helm:
        releases:
          - name: vector-store
            chartPath: charts/vector-store
            namespace: genai-vectors
            createNamespace: true
            setValues:
              api.image: hv-local/vector-store-api
              api.tag: v1
              indexer.image: hv-local/vector-store-indexer
              indexer.tag: v1
