auth:
  rootUser: minioadmin
  rootPassword: minioadmin

defaultBuckets: "vectors"

service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m