apiVersion: v1
kind: Service
metadata:
  name: {{ include "vector-store.fullname" . }}-api
  labels:
    {{- include "vector-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vector-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
