# Production Configuration

[aws]
# AWS credentials (optional - will use environment variables if not set)
# access_key_id = "your_access_key"
# secret_access_key = "your_secret_key"
# Use IAM roles in production instead of hardcoded credentials

[server]
host = "0.0.0.0"
port = 8080
log_level = "info"

[storage]
bucket_name = "genai-vectors-prod"
region = "us-east-1"
# endpoint not set for production (uses AWS S3)

[vector]
default_dimension = 256
default_batch_size = 5000
default_top_k = 10
default_metric = "cosine"

[cache]
vector_cache_dir = "/data/cache"
enable_cache = true
cache_size_mb = 4096

[indexing]
shard_size = 50000
max_shards_per_index = 1000
enable_background_indexing = true

[test]
bucket_prefix = "genai-vectors-test-prod"
dimension = 256
small_scale_vectors = 1000
large_scale_vectors = 500000

[monitoring]
enable_metrics = true
metrics_port = 9090
